RED := \033[31m
GREEN := \033[32m
YELLOW := \033[33m
BLUE := \033[34m
RESET := \033[0m

NAME = Simulator
CLASS_FOLDER = classes
SOURCE = sources.txt

build:

run:

clean:
	@rm $(SOURCE)
	@rm -rf $(CLASS_FOLDER)
	@echo "$(GREEN)Cleaning done!$(RESET)"

.PHONY: run build clean