name: inquisitor

services:


  ftp-server:
    build:
      context: ./ftp_server
      dockerfile: Dockerfile
    networks:
      custom_net:
        ipv4_address: 10.5.0.17

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    cap_drop:
      - ALL
    networks:
      custom_net:
        ipv4_address: 10.5.0.18

  poison:
    build:
      context: ./poison
      dockerfile: Dockerfile
    cap_drop:
      - ALL
    cap_add:
      - NET_RAW
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.send_redirects=0
    networks:
      custom_net:
        ipv4_address: 10.5.0.19

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
